### PR TITLE
Added date option to see a particular duration of work

### LINKED ISSUE #3: Add a option on the home screen for the user to select the duration for which they want to see their works
The user can select the time(in days) for which they wan't their works to be displayed. A dropdown menu would do the job!

### PR DESCRIPTION
**Pull request by shahidsiddiqui786**
Fixes #3

### CODE REVIEW

**Comment by sarthakm21** [comment]
Hey @shahidsiddiqui786 great work man. Although I'm still reviewing some parts of the code, till now it works well. I'll merge the pr soon :)

**Comment by shahidsiddiqui786** [comment]
Hey @sarthakm21 
Are you still reviewing this pr?

**Comment by sarthakm21** [comment]
@shahidsiddiqui786 sorry for the delay.
About this HTML date element you used, I read that it is not supported at all in Safari browser. Can you try to look for some alternative for this? You are free to use any external date picker libraries that will do the job.

**Comment by sarthakm21** [comment]
@shahidsiddiqui786 any updates?

**Comment by shahidsiddiqui786** [comment]
@sarthakm21 
Actually I was busy 
I will do it today.

**Comment by shahidsiddiqui786** [comment]
hey @sarthakm21 
Added a datepicker library which support IE10+, Safari 6+, Firefox, and Chrome

**Comment by sarthakm21** [comment]
@shahidsiddiqui786 Looks good. Some issues with reloading though. The date selected cannot be retained in this way.
I want to try to shift it to ajax if I can. So, I prefer to not merge this in the main branch yet. Can you create a new PR with merge request in the date-picker branch of this repo so that I can see if I am able to add something before merging into main branch?
Thanks

**Comment by sarthakm21** [comment]
Also, see if you can squash the commits into a single one. Would be helpful :)

**Comment by shahidsiddiqui786** [comment]
> 
> 
> @shahidsiddiqui786 Looks good. Some issues with reloading though. The date selected cannot be retained in this way.
> I want to try to shift it to ajax if I can. So, I prefer to not merge this in the main branch yet. Can you create a new PR with merge request in the date-picker branch of this repo so that I can see if I am able to add something before merging into main branch?
> Thanks

ok,done

**Comment by shahidsiddiqui786** [comment]
> 
> 
> Also, see if you can squash the commits into a single one. Would be helpful :)

ok ,I will try

**Pull request closed without merging**
