### PR TITLE
Designed Profile page

### PR DESCRIPTION
**Pull request by IC1101Virgo**
I have designed the profile page. 
Tell me if any changes are required. 
Thanks
Issue #30 

profilepic

### CODE REVIEW

**Comment by sarthakm21** [comment]
A few things to do:
- Wrap all of this in the div with container class so that it does not take up all the area
- Make the work cards look like the way they do on the home page and the inspire me page. (The classes are already defined for those cards, so use them only. No need for new ones)
- Fix the alignment 
- And maybe you could change the color theme so that it matches the overall website
Thanks :)

**Comment by sarthakm21** [comment]
And please make the pr to **Profile branch**

**Comment by IC1101Virgo** [comment]
@sarthakm21 ok on it 😄 Also I am unable to do in Profile branch it sends me an error

**Comment by sarthakm21** [comment]
What is the error?

**Comment by IC1101Virgo** [comment]
profilepage

Did the required changes

**Comment by IC1101Virgo** [comment]
profilepage2
This the page.

**Comment by IC1101Virgo** [comment]
profilepage3
Here is the one with latest changes 🐵

**Pull request closed without merging**
