### PR TITLE
header background changed,text changed

### PR DESCRIPTION
**Pull request by shahidsiddiqui786**
how it looks now
Screenshot_2020-10-12 Work Track(4)

### CODE REVIEW

**Comment by sarthakm21** [comment]
The background image looks great! The emojis though look slightly out of the alignment. Maybe you can use font awesome icons instead? 
And shouldn't the header text be
See what 👥 are working on instead of 
See the ...... ?

**Comment by shahidsiddiqui786** [comment]
> 
> 
> The background image looks great! The emojis though look slightly out of alignment. Maybe you can use font awesome icons instead?
> And shouldn't the header text be
> See what 👥 are working on instead of
> See the ...... ?

cha
Screenshot_2020-10-12 Work Track(5)
nged!

**Comment by sarthakm21** [comment]
Great! One last tiny thing though. I noticed you added font awesome CDN in the header.ejs file but I already have it included in the footer.ejs. Unless it is causing some error, I think we can get rid of the CDN link in the header file.......

**Comment by shahidsiddiqui786** [comment]
> 
> 
> Great! One last tiny thing though. I noticed you added font awesome CDN in the header.ejs file but I already have it included in the footer.ejs. Unless it is causing some error, I think we can get rid of the CDN link in the header file.......

Done

**Comment by sarthakm21** [comment]
Awesome! Thanks :)

**Pull request merged**
