### PR TITLE
Added text shadow to header in new users page

### LINKED ISSUE #18: Change the Header text for a new user to make it more visible
Currently, it looks like this.

one

Its not very clearly visible. Change the top text's styles to increase its visibility. 
**Do not change anything that will affect other elements as well**

### PR DESCRIPTION
**Pull request by sanskar-p**
Resolves #18 
Add text shadow to the header text and also changed the color of the 'Add Work' link. It is underlined to denote that it's a link and the text-shadow color lightens when you hover the cursor over it.

image

On hover: 
Screenshot from 2020-10-14 22-21-50

### CODE REVIEW

**Comment by sarthakm21** [comment]
Hey @sanskar-p, sorry for checking so late but can you change the color of AddWork link instead of that underline? It kinda looks weird.

**Comment by sanskar-p** [comment]
Okay @sarthakm21, what do you suggest I change the colour to?

**Comment by sarthakm21** [comment]
I think the standard blue-purple color of the anchor tags should do. As far as I remember the other links on the page also have the default color. Although, if that is not the case, you can use the color that the other links use :)

**Comment by sanskar-p** [comment]
In my opinion, the default color doesn't look so great with purple-white text around it. What are your thoughts?
image

**Comment by sarthakm21** [comment]
Ig you're right. I'll leave it upto you then. You can choose whichever color you find suitable.

**Comment by sanskar-p** [comment]
I've made the links bold and italic. And they get a text-shadow on hover.
image
On hover:
Screenshot from 2020-10-16 22-18-22

**Comment by sarthakm21** [comment]
Thanks @sanskar-p :). Merging!

**Pull request merged**
