### PR TITLE
Added a better background throughout the app

### LINKED ISSUE #4: Add a better background throughout the app
It's plain white right now, and rather boring tbh. Select and add a new backgound that adds some life to the app. Nothing too flashy though. Something that matches with the overall theme of the app.

### PR DESCRIPTION
**Pull request by alkatrivedi**
Fixes #4 

**Changes Made**

- Add background color to the home page, inspireme page, addwork page and statistics page.

Some screenshots of the changes made are:

### CODE REVIEW

**Comment by alkatrivedi** [comment]
For now I have added the background color to statistics page also but if you don't like it I'll remove that.

**Comment by sarthakm21** [comment]
Hey @alkatrivedi, some issues with this
1. Why have you added styles using javascript ?. Please switch that to css. The css files are present in public directory.
2. I'm not a big fan of the way add work section looks. And also, using different color schemes in different sections is not a good idea tbh. So can you just use the color you used in the inspire me section?
3. Lastly, remove the background from the statistics section please. I liked it better the way it was.
Thanks :)

**Comment by alkatrivedi** [comment]
Alright! will do the desired changes.

**Comment by alkatrivedi** [comment]
Hey, I have to use javascript to add class name to the body tag for any particular page. Otherwise it seems that there's no way to give color to three pages except only one page(i.e., statistics page).

May I add class to body tag using javascript and then use that class in css file to give the color to body?

**Comment by sarthakm21** [comment]
Instead of that, you can just wrap the content into a wrapper div, give it a class, and then apply the styles to it.

**Comment by alkatrivedi** [comment]
I tried, but it's not covering the upper and lower part of the container. Even I tried to give that div to cover whole body that's also not working.

Here's the screenshot of the problem
Capture

**Comment by sarthakm21** [comment]
Can you share the code changes you made? CSS and all..........

**Comment by alkatrivedi** [comment]
Yeah sure!

Here I make a div and give it a class stylehome


And here's the corresponding CSS code:

**Comment by sarthakm21** [comment]
ig you are right. I think the margins of the cards are causing this error. If you cannot find any other alternative, then you can use js for adding the class name :)

**Comment by alkatrivedi** [comment]
Hey I resloved the error!

Here's the screenshots of the final changes:

Home Page:


AddWork Page:


Statistics Page:


InspireMe Page:


If still anything you wanted to change do let me know. I'll do that.
Thank you:)

**Comment by sarthakm21** [comment]
Just one last thing. Squash these commits into a single commit. Refer: 
[Squashing commits into one](https://www.youtube.com/watch?v=2E23I9PzplM)

**Comment by alkatrivedi** [comment]
Done.

**Pull request merged**
